- name: Install PHP and modules
  dnf: 
    name: 
      - php
      - php-mysqlnd
      - php-cli
      - php-gd
      - php-xml
      - php-mbstring
    state: present

- name: Restart Apache to load PHP
  systemd:
    name: httpd
    state: restarted
